### ISSUE TITLE
missing script

### ISSUE THREAD

**Issue by willDTF** [EmberLightVFX/Kitsu-Publisher#2]
hello, 
we can't run the bat file without env\Scripts\activate.bat 

running the python directly leads to missing libraries, 
can you share the activate.bat content please ?

**Comment by EmberLightVFX** [comment]
You need to create a virtual environment through python first and install the needed libraries. Run these commands inside the Kitsu-Publisher folder:
(for windows)
```
python -m venv env
env\Scripts\activate.bat
pip install -r requirements.txt
```

You can now ether start Kitsu Publisher by running `python "Kitsu Publisher.py"` while inside the virtual environment.
If you're outside you can start Kitsu Publisher by executing the .bat file

**Comment by willDTF** [comment]
ho, didn't see that it need a venv, thanks !
